//
//  SplashScreenInteractor.swift
//  Pods
//
//  Created by John Patrick Teruel on 4/19/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashScreenBusinessLogic
{
  func doSomething(request: SplashScreen.Something.Request)
}

protocol SplashScreenDataStore
{
  //var name: String { get set }
}

class SplashScreenInteractor: SplashScreenBusinessLogic, SplashScreenDataStore
{
  var presenter: SplashScreenPresentationLogic?
  var worker: SplashScreenWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SplashScreen.Something.Request)
  {
    worker = SplashScreenWorker()
    worker?.doSomeWork()
    
    let response = SplashScreen.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
