//
//  HomeModels.swift
//  Pods
//
//  Created by John Patrick Teruel on 4/24/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AniListKtModule

enum Home
{
    // MARK: Use cases
    
    enum UserProfile
    {
        struct Request
        {
        }
        struct Response
        {
            let user: UserInfo
        }
        struct ViewModel
        {
            let userImage: URL?
        }
    }
}
