//
//  HomePresenter.swift
//  Pods
//
//  Created by John Patrick Teruel on 4/24/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLib

protocol HomePresentationLogic: CanPresentHUD, CanPresentAlert
{
    func presentUserProfile(response: Home.UserProfile.Response)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentUserProfile(response: Home.UserProfile.Response) {
        DispatchQueue.main.async {
            self.viewController?.displayUserProfile(
                viewModel: .init(
                    userImage: try? response.user.avatar?.medium?.asURL()
                )
            )
        }
    }
    
    func presentHUD() {
        DispatchQueue.main.async {
            self.viewController?.displayHUD()
        }
    }
    
    func dismissHUD() {
        DispatchQueue.main.async {
            self.viewController?.dismissHUD()
        }
    }
    
    func presentAlert(title: String, message: String, buttonTitle: String) {
        DispatchQueue.main.async {
            self.viewController?.displayAlert(title: title, message: message, actionTitle: buttonTitle)
        }
    }
}
