//
//  HomeInteractor.swift
//  Pods
//
//  Created by John Patrick Teruel on 4/24/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func initialLoad()
}

protocol HomeDataStore
{
    var moduleData: LandingModuleData! { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    var moduleData: LandingModuleData!
    
    // MARK: Do something
    
    func initialLoad() {
        Task {
            self.presenter?.presentHUD()
            do {
                let userInfo = try await moduleData.userService.getUserInfo()
                print("User Info: \(userInfo)")
                self.presenter?.presentUserProfile(response: .init(user: userInfo))
            } catch {
                self.presenter?.presentAlert(title: "Error", message: error.localizedDescription)
            }
            self.presenter?.dismissHUD()
        }
    }
}
