//
//  LoginPresenter.swift
//  Pods
//
//  Created by John Patrick Teruel on 4/19/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLib

protocol LoginPresentationLogic: CanPresentAlert, CanPresentHUD
{
    func presentAuthorizationWebView(response: Login.Authorization.Response)
    func dismissWebView()
}

class LoginPresenter: LoginPresentationLogic
{
    weak var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentAuthorizationWebView(response: Login.Authorization.Response)
    {
        let viewModel = Login.Authorization.ViewModel(oauthURL: response.oauthURL)
        viewController?.displayAuthorizationWebView(viewModel: viewModel)
    }
    
    func dismissWebView() {
        viewController?.dismissWebView()
    }
    
    func presentAlert(title: String, message: String, buttonTitle: String) {
        viewController?.displayAlert(title: title, message: message, actionTitle: buttonTitle)
    }
    
    func presentHUD() {
        viewController?.displayHUD()
    }
    
    func dismissHUD() {
        viewController?.dismissHUD()
    }
}
