//
//  LoginViewController.swift
//  Pods
//
//  Created by John Patrick Teruel on 4/19/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import WebKit
import CoreLib

protocol LoginDisplayLogic: AnyObject, CanDisplayAlert, CanDisplayHUD
{
    func displayAuthorizationWebView(viewModel: Login.Authorization.ViewModel)
    func dismissWebView()
}

class LoginViewController: UIViewController, LoginDisplayLogic
{
    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic & LoginDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        interactor?.restoreSession()
    }
    
    @IBAction func didTapAuthorizeButton(_ sender: UIButton) {
        authorizeUser()
    }
    
    // MARK: Authorize
    
    func authorizeUser()
    {
        let request = Login.Authorization.Request()
        interactor?.requestAuthorization(request: request)
    }
    
    func displayAuthorizationWebView(viewModel: Login.Authorization.ViewModel) {
        router?.routeToAuthorizationWebView(url: viewModel.oauthURL)
    }
    
    func dismissWebView() {
        router?.dismissWebViewController()
    }
}

extension LoginViewController: WKNavigationDelegate {
    func webView(_ webView: WKWebView, didReceiveServerRedirectForProvisionalNavigation navigation: WKNavigation!) {
        interactor?.handleRedirect(request: .init(url: webView.url))
    }
}
